# Generated by Django 6.0.7 on 2026-08-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=True, help_text='Presence status — offline agents are skipped by auto-assignment'),
        ),
    ]
