# Generated by Django 6.0.7 on 2026-08-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_conversation_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='handoff_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
